server:
  port: 8080
  servlet:
    context-path: /products
spring:
  application:
    name: products
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
job:
  time:
    refreshCache: 500000